### ISSUE TITLE
feat : make name blocks rectangular rather than square 

### ISSUE THREAD

**Issue by wise-toddler** [SST-OSS/seating-old#27]
make name blocks rectangular rather than square

**Comment by probablyArth** [comment]
no

**Comment by probablyArth** [comment]
Not sure if it will look better, rounded looks arguably better. We could do a poll.

**Comment by maybeabhinav** [comment]
Yeah, I think it looks good as it is right now.

**Comment by wise-toddler** [comment]
aree samjhe nhi tum aate hain tumhare room mei batane
